### ISSUE TITLE
Clicking on Maps makes the app crash

### ISSUE THREAD

**Issue by ajayramak** [G-Node/GCA-Android#13]
Dear GCA-Android development team

I am using the app on Cyanogenmod 11 based on Android 4.4.4. Clicking on Maps crashes the app. This happens with both wifi and mobile data connection. This maybe because I don't have google maps. A redirect to the google maps mobile website might fix it?

Sincerely
Ajay

**Comment by segensreich** [comment]
Dear Ajay 

Thanks for reporting! 

Its most probably because you have disabled play services.  As this will not happen when the app is installed regularly i think we can close the issue for the time being.

Thanks anyhow

Cheers
